version: '3.9'
services:
  web:
    build: .
    command:  gunicorn DjangoRestApi.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
#      - web_django:/app
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 1111:80
    depends_on:
      - web
  client:
    build: client/
    command: python ./client.py
    network_mode: host
    volumes:
      - ./client:/client
    depends_on:
      -  web
      -  nginx
volumes:
# web_django:
   static_volume:
