version: '3.9'
services:
#  jenkins:
#    build: build/
#    container_name: jenkins-server
#    privileged: true
#    hostname: jenkinsserver
#    user: root
#    labels:
#      com.example.description: "Jenkins-Server by DigitalAvenue.dev"
#    ports:
#      - "8088:8080"
#      - "50001:50000"
#    networks:
#      jenkins_net:
#        aliases:
#          - jenkins_net
#    volumes:
#     - jenkins_home:/var/jenkins_home
#     - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - client
  web:
    build:
      context: .
      network: host
    command:  gunicorn build.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
#      - web_django:/app
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 1111:80
    depends_on:
      - web
  client:
    build: client/
    command: python client.py
    network_mode: host
    volumes:
      - ./client:/client
    depends_on:
      -  web
      -  nginx

volumes:
# web_django:
   static_volume:
#   jenkins_home:
#
#networks:
#  jenkins_net:
