version: '3.9'
services:
#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins-server
#    privileged: true
#    hostname: jenkinsserver
#    user: root
#    labels:
#      com.example.description: "Jenkins-Server by DigitalAvenue.dev"
#    ports:
#      - "8083:8080"
#      - "50000:50000"
#    networks:
#      jenkins_net:
#        aliases:
#          - jenkins_net
#    volumes:
#     - jenkins_data:/var/jenkins_home
#     - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    command:  gunicorn DjangoRestApi.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
#      - web_django:/app
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 1111:80
    depends_on:
      - web
  client:
    build: client/
    command: python ./client.py
    network_mode: host
    volumes:
      - ./client:/client
    depends_on:
      -  web
      -  nginx
      -  jenkins

volumes:
# web_django:
   static_volume:
#   jenkins_data:
#
#networks:
#  jenkins_net:
