# Generated by Django 3.2.6 on 2021-08-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="apis.product",
            ),
        ),
    ]
