# Generated by Django 3.2.6 on 2021-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_auto_20210830_0945"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="level",
            field=models.TextField(default=676),
            preserve_default=False,
        ),
    ]
