# Generated by Django 3.2.6 on 2021-08-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_auto_20210830_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citys",
                to="apis.country",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="city",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotels",
                to="apis.city",
            ),
        ),
    ]
